apiVersion: apps/v1
kind: Deployment
metadata:
name: showcase-app
namespace: showcase
spec:
replicas: 2
selector:
matchLabels:
app: showcase
template:
metadata:
labels:
app: showcase
spec:
containers:
- name: app
image: REPLACE_WITH_ECR_IMAGE # e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/showcase:latest
ports:
- containerPort: 8080
env:
- name: S3_BUCKET
value: "REPLACE_WITH_S3_BUCKET"
resources:
limits:
cpu: "500m"
memory: "512Mi"
requests:
cpu: "200m"
memory: "256Mi"