name: CI-CD to EKS


on:
push:
branches: ["main"]


jobs:
build-and-deploy:
runs-on: ubuntu-latest


permissions:
contents: read
id-token: write


steps:
- name: Checkout
uses: actions/checkout@v4


- name: Configure AWS credentials
uses: aws-actions/configure-aws-credentials@v2
with:
aws-region: ${{ secrets.AWS_REGION }}
role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} # optional; or use aws-access-key-id + secret


- name: Login to ECR
id: login-ecr
uses: aws-actions/amazon-ecr-login@v1


- name: Build, tag, and push image
env:
ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
IMAGE_TAG: ${{ github.sha }}
run: |
docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


- name: Update kubeconfig for EKS
run: |
aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}


- name: Replace image in k8s manifest and deploy
run: |
IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
sed -i "s|REPLACE_WITH_ECR_IMAGE|$IMAGE|g" k8s/deployment.yaml
sed -i "s|REPLACE_WITH_S3_BUCKET|${{ secrets.S3_BUCKET }}|g" k8s/deployment.yaml
kubectl apply -f k8s/namespace.yaml
kubectl apply -f k8s/deployment.yaml
kubectl apply -f k8s/service.yaml


